## AJAX (Asynchronous Javascript And XML)

but now a days it is

## AJAJ (Asynchronous Javascript And Json)

---

> fetch have an issue, when the response is 404 or 500, it wont fall to the catch block. only network error is rejected and being caught in the cactch block.
>
> ##### Fetch promises only reject with a TypeError when a network error occurs. Since 4xx and 5xx responses aren't network errors, there's nothing to catch. You'll need to throw an error yourself to use Promise#catch.
>
> ##### A fetch Response conveniently supplies an ok , which tells you whether the request succeeded. Something like this should do the trick:

> ```js
> fetch(url)
>   .then((response) => {
>     if (response.ok) {
>       return response.json();
>     }
>     throw new Error("Something went wrong");
>   })
>   .then((responseJson) => {
>     // Do something with the response
>   })
>   .catch((error) => {
>     console.log(error);
>   });
> ```

## async await

---

> asynchronous function returns a promise, though we are not explicitly returning any.

> ```js
> async func greet(){
> return "Hello"
> }
>
> greet.then((res) => {console.log(res)})
>
>
> ```

> **await:**
>
> - using await will pause the execution of the function till that promise is resolved , (till that API call has been made).
